<a href="https://colab.research.google.com/github/samikshakak/ML_ASSIGNMENT/blob/main/assig1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]

print(reversed_arr)


[5 4 6 3 2 1]


In [ ]:
import numpy as np


array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])


flattened_array_flatten = array1.flatten()
print("Flattened using flatten():", flattened_array_flatten)


flattened_array_ravel = array1.ravel()
print("Flattened using ravel():", flattened_array_ravel)


Flattened using flatten(): [1 2 3 2 4 5 1 2 3]
Flattened using ravel(): [1 2 3 2 4 5 1 2 3]


In [ ]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

comparison = arr1 == arr2
print(comparison)


[[ True  True]
 [ True  True]]


In [ ]:
import numpy as np

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])


counts = np.bincount(x)

most_frequent_value = np.argmax(counts)

indices = np.where(x == most_frequent_value)[0]

print("Array x:")
print("Most frequent value:", most_frequent_value)
print("Indices of the most frequent value:", indices)


Array x:
Most frequent value: 1
Indices of the most frequent value: [0 5 7 8 9]


In [ ]:
import numpy as np

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])


counts = np.bincount(y)

most_frequent_value = np.argmax(counts)

indices = np.where(y == most_frequent_value)[0]

print("Array y:")
print("Most frequent value:", most_frequent_value)
print("Indices of the most frequent value:", indices)


Array y:
Most frequent value: 1
Indices of the most frequent value: [0 1 2]


In [ ]:
import numpy as np


gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')


sum_all_elements = np.sum(gfg)


sum_row_wise = np.sum(gfg, axis=1)


sum_column_wise = np.sum(gfg, axis=0)

print("Sum of all elements:", sum_all_elements)
print("Sum of all elements row-wise:", sum_row_wise)
print("Sum of all elements column-wise:", sum_column_wise)


Sum of all elements: 45
Sum of all elements row-wise: [[14]
 [16]
 [15]]
Sum of all elements column-wise: [[20  9 16]]
Sum of all elements: 45
Sum of all elements row-wise: [[14]
 [16]
 [15]]
Sum of all elements column-wise: [[20  9 16]]


In [ ]:
import numpy as np


n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])


sum_diagonal = np.trace(n_array)
print("Sum of diagonal elements:", sum_diagonal)


eigenvalues, eigenvectors = np.linalg.eig(n_array)
print("Eigenvalues of the matrix:", eigenvalues)
print("Eigenvectors of the matrix:\n", eigenvectors)


inverse_matrix = np.linalg.inv(n_array)
print("Inverse of the matrix:\n", inverse_matrix)


determinant = np.linalg.det(n_array)
print("Determinant of the matrix:", determinant)


Sum of diagonal elements: 176
Eigenvalues of the matrix: [98.16835147 28.097044   49.73460452]
Eigenvectors of the matrix:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse of the matrix:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant of the matrix: 137180.0000000001


In [ ]:
import numpy as np

p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])


product1 = np.dot(p1, q1)
print("Product of matrices p1 and q1:\n", product1)

p1_flat = p1.flatten()
q1_flat = q1.flatten()

cov_matrix1 = np.cov(p1_flat, q1_flat, bias=True)
print("Covariance matrix between flattened p1 and q1:\n", cov_matrix1)


Product of matrices p1 and q1:
 [[16 19]
 [26 31]]
Covariance matrix between flattened p1 and q1:
 [[0.5  0.75]
 [0.75 1.25]]


In [ ]:
import numpy as np


x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])


inner_product = np.dot(x, y.T)
print("Inner product (matrix multiplication):\n", inner_product)


outer_product_x_row1_y_row1 = np.outer(x[0], y[0])

outer_product_x_row2_y_row2 = np.outer(x[1], y[1])

print("Outer product of the first rows (x[0] and y[0]):\n", outer_product_x_row1_y_row1)
print("Outer product of the second rows (x[1] and y[1]):\n", outer_product_x_row2_y_row2)


X, Y = np.meshgrid(x, y, indexing='ij')
cartesian_product = np.vstack([X.ravel(), Y.ravel()]).T

print("Cartesian product:\n", cartesian_product)


Inner product (matrix multiplication):
 [[17 52]
 [13 62]]
Outer product of the first rows (x[0] and y[0]):
 [[ 2 10  0]
 [ 3 15  0]
 [ 4 20  0]]
Outer product of the second rows (x[1] and y[1]):
 [[15 30  9]
 [10 20  6]
 [45 90 27]]
Cartesian product:
 [[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


In [ ]:
import numpy as np


array = np.array([[1, -2, 3], [-4, 5, -6]])


abs_array = np.abs(array)


flattened_array = array.flatten()
percentiles_flattened = np.percentile(flattened_array, [25, 50, 75])
percentiles_columns = np.percentile(array, [25, 50, 75], axis=0)
percentiles_rows = np.percentile(array, [25, 50, 75], axis=1)


mean_flattened = np.mean(flattened_array)
median_flattened = np.median(flattened_array)
std_flattened = np.std(flattened_array)

mean_columns = np.mean(array, axis=0)
median_columns = np.median(array, axis=0)
std_columns = np.std(array, axis=0)

mean_rows = np.mean(array, axis=1)
median_rows = np.median(array, axis=1)
std_rows = np.std(array, axis=1)

(abs_array, percentiles_flattened, percentiles_columns, percentiles_rows,
 mean_flattened, median_flattened, std_flattened,
 mean_columns, median_columns, std_columns,
 mean_rows, median_rows, std_rows)


(array([[1, 2, 3],
        [4, 5, 6]]),
 array([-3.5, -0.5,  2.5]),
 array([[-2.75, -0.25, -3.75],
        [-1.5 ,  1.5 , -1.5 ],
        [-0.25,  3.25,  0.75]]),
 array([[-0.5, -5. ],
        [ 1. , -4. ],
        [ 2. ,  0.5]]),
 -0.5,
 -0.5,
 3.8622100754188224,
 array([-1.5,  1.5, -1.5]),
 array([-1.5,  1.5, -1.5]),
 array([2.5, 3.5, 4.5]),
 array([ 0.66666667, -1.66666667]),
 array([ 1., -4.]),
 array([2.05480467, 4.78423336]))

In [ ]:
import numpy as np


a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])


floor_values = np.floor(a)
ceiling_values = np.ceil(a)
truncated_values = np.trunc(a)
rounded_values = np.round(a)

(floor_values, ceiling_values, truncated_values, rounded_values)


(array([-2., -2., -1.,  0.,  1.,  1.,  3.]),
 array([-1., -1., -0.,  1.,  2.,  2.,  3.]),
 array([-1., -1., -0.,  0.,  1.,  1.,  3.]),
 array([-2., -2., -0.,  0.,  2.,  2.,  3.]))

In [ ]:
import numpy as np


array = np.array([10, 52, 62, 16, 16, 54, 453])


sorted_array = np.sort(array)


indices_sorted_array = np.argsort(array)


smallest_elements = np.partition(array, 4)[:4]


largest_elements = np.partition(array, -5)[-5:]

(sorted_array, indices_sorted_array, smallest_elements, largest_elements)


(array([ 10,  16,  16,  52,  54,  62, 453]),
 array([0, 3, 4, 1, 5, 2, 6]),
 array([16, 10, 16, 52]),
 array([ 16,  52,  62,  54, 453]))

In [ ]:
import numpy as np


array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])


integer_elements = array[array % 1 == 0]


float_elements = array[array % 1 != 0]

(integer_elements, float_elements)


(array([1., 2., 3., 2.]), array([1.2, 2.2]))

In [ ]:
import numpy as np
from PIL import Image

def img_to_array(path, save_path_rgb='rgb_image.txt', save_path_gray='gray_image.txt'):

    img = Image.open(path)


    if img.mode == 'RGB':
        img_array = np.array(img)

        np.savetxt(save_path_rgb, img_array.reshape(-1, img_array.shape[-1]), fmt='%d')
    elif img.mode == 'L':
        img_array = np.array(img)

        np.savetxt(save_path_gray, img_array, fmt='%d')
    else:
        raise ValueError("Unsupported image mode")

    return img_array


from google.colab import files
uploaded = files.upload()

for file_name in uploaded.keys():
    img_array = img_to_array(file_name)
    import numpy as np
import matplotlib.pyplot as plt


def load_rgb_image(file_path, original_shape):

    flat_array = np.loadtxt(file_path, dtype=int)
    img_array = flat_array.reshape(original_shape)
    return img_array

def load_gray_image(file_path):
    img_array = np.loadtxt(file_path, dtype=int)
    return img_array


uploaded = files.upload()

for file_name in uploaded.keys():
    if 'rgb' in file_name:

        rgb_img_array = load_rgb_image(file_name, (height, width, 3))
        plt.imshow(rgb_img_array)
        plt.show()
    elif 'gray' in file_name:
        gray_img_array = load_gray_image(file_name)
        plt.imshow(gray_img_array, cmap='gray')
        plt.show()



Saving img.jpg to img (1).jpg
